name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - name: Test Go
      run: echo "$PATH" && which go
        
    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.85.0
        TARGET_REPO: quantumontpellier/quantumontpellier.github.io
        TOKEN: ${{ secrets.PAT_TOKEN }}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # Do not add CNAME for the moment
        #CNAME: www.jameswright.xyz
